apiVersion: v1
kind: Service
metadata:
  name: build2018-rating-web
  labels:
    name: build2018-rating-web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: build2018-rating-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build2018-rating-web
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build2018-rating-web
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        app: build2018-rating-web
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: build2018-rating-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: SITE_API
          value: "{{.Values.apiSites}}"
        - name: SUBJECT_API
          value: "{{.Values.apiSubjects}}"
        - name: RATING_API
          value: "{{.Values.apiRatings}}"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080